### ISSUE TITLE
Pokken tournement wont download?

### ISSUE THREAD

**Issue by xXCheeseWizardXx** [DanTheMan827/uTikDownloadHelper#15]
![screenshot 64](https://cloud.githubusercontent.com/assets/21300797/20248683/e5edcc4e-a99d-11e6-9896-f1936f074518.png)
![screenshot 61](https://cloud.githubusercontent.com/assets/21300797/20248684/e5f643a6-a99d-11e6-87c8-df6c684df3d5.png)
![screenshot 62](https://cloud.githubusercontent.com/assets/21300797/20248685/e5f663ea-a99d-11e6-9f32-97f3ec7b12a3.png)
![screenshot 63](https://cloud.githubusercontent.com/assets/21300797/20248686/e5fbf076-a99d-11e6-92d0-c57e2d429374.png)
![screenshot 65](https://cloud.githubusercontent.com/assets/21300797/20248688/edf0dddc-a99d-11e6-8615-ccec50e9074f.png)
Pokken tournement wont download and  im pretty sure i have everthing in the right place???
![15049682_1137333586321085_354398556_n](https://cloud.githubusercontent.com/assets/21300797/20248696/344a76e4-a99e-11e6-83c8-7d21f78f5ac3.jpg)

**Comment by DarkenLX** [comment]
im having the same issue  every game installs that is suppose to except pokken and oddly it say the folder is install/POKK_N TOURNAMENT (USA)  but the folder on the sd is not named that it is spelled w/o the "_" in fact there is no folder spelled  "POKK_N TOURNAMENT" is it looking for a different folder?

**Comment by DanTheMan827** [comment]
Change the É to something else, that messes up wup installer.

On Wed, Nov 16, 2016 at 5:11 PM DarkenLX <notifications@github.com> wrote:

im having the same issue every game installs that is suppose to except
pokken and oddly it say the folder is install/POKK_N TOURNAMENT (USA) but
the folder on the sd is not named that it is spelled w/o the "_" in fact
there is no folder spelled "POKK_N TOURNAMENT" is it looking for a
different folder?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DanTheMan827/uTikDownloadHelper/issues/15#issuecomment-261102969>,
or mute the thread

**Comment by systemeth** [comment]
I'm having the same issue in terms of what the issue title says; the uTik won't download Pokken.
It just tells me "The following title has an encountered an error: POKKÉN TOURNAMENT." and it doesn't download the game. I can download other things just fine (and installed other things just fine) but not this one for some reason.

**Comment by MatthewOverall** [comment]
@systemeth Did you change the É to an E instead?

**Comment by systemeth** [comment]
No, I don't know how to do that in the first place. I don't even see an option with which to do that.
uTik just shows a list of all the stuff I can download, I chose Pokken, clicked Downlaod, and then what I said above is what happens.

**Comment by DanTheMan827** [comment]
The solution is simple...

Right click on the folder that was created and take out the É in POKK**É**N TOURNAMENT so that it just reads **POKKEN TOURNAMENT**

The same is true for any other "special" characters in the folder names like ™ and ®

**Comment by systemeth** [comment]
No folder is being created in the first place. I'm not talking about having a problem when I actually go to install the game on the Wii U side, I'm talking about a problem when I go to download the shit on my PC. It errors right after I click Download (while it's attempting to download title.tik it looks like).

**Comment by Dezaimasu** [comment]
@systemeth 
Absolutely same problem, can't download any games with non-standard symbols in the title. I'm not sure if it should be like that.
For example Taiko no Tatsujin Atsumete★ TomodachiDaisakusen! 
I can use title.tik to download the game because then there's no forbidden(?) symbols in folder name, only Title ID, but I can't download DLC that way, the checkbox for DLC becomes inactive (probably because it's rednand-only), and there's no separate .tik file for DLC.

Once again, I'm not talking about wupinstaller or anything else, just downloading via uTikDownloadHelper

**Comment by ImplyingKinpatsu** [comment]
I'm having the same issue with the same content as @Dezaimasu
