### ISSUE TITLE
Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by heymanwhatman** [DanTheMan827/uTikDownloadHelper#33]
I get this message whenever  I try to open this. I don't know if this has anything to do with the application or with my pc itself. It worked perfectly for a while, but it just recently started giving me this error. I'm not very technologically inclined, though, so I won't understand anything too complex.

**Comment by piper12345** [comment]
Im getting this too and never had a problem until about 3 hours ago.

**Comment by DanTheMan827** [comment]
The problem lies in the fact that the owner of the website forgot to renew their domain.

I don't know if it's a permanent situation or just temporary.

As a workaround, you can add the following to your hosts file (replacing website.xyz with the _actual_ domain)

    95.183.50.10 website.xyz
    95.183.50.10 wiiu.website.xyz
    95.183.50.10 3ds.website.xyz

If you don't know how to modify the hosts file, you need to find notepad in the start menu, right click, run as administrator.

Then you open up the file **C:\Windows\System32\drivers\etc\hosts** (you can copy this and just paste it into the name field)

**Comment by fadetonoir** [comment]
Just wanted to say that the IP address above no longer seems to work but the site seems to have migrated to a new domain (same name, different extension) and the IP address for that is 104.129.56.137, so editing the hosts file as above but with that IP address instead is working for me.

**Comment by piper12345** [comment]
Do I do this by actually opening utik in notepad? or literally copying and pasting C:\Windows\System32\drivers\etc\hosts? Asking because Im not sure where to put 104.129.56.137.  Thank you

**Comment by IohanSardinha** [comment]
The site from where you're getting the keys is probably off, so if you delete the file from utik in your AppData/local and start the utik.exe again you can choose another site to get the keys
